"use server";

import db from "@/lib/db";
import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

type ContactFormData = {
  firstName: string;
  lastName: string;
  email: string;
  vnnumber: string;
  message: string;
};

export async function handleContactForm(data: ContactFormData) {
  try {
    const { firstName, lastName, email, vnnumber, message } = data;

    console.log("Received contact form data:", data);

    // Validate required fields
    if (!firstName || !lastName || !email || !message) {
      return NextResponse.json(
        { success: false, error: "Required fields are missing" },
        { status: 400 }
      );
    }

    // Save to database
    const contact = await db.contact.create({
      data: {
        firstName,
        lastName,
        email,
        vnnumber,
        message,
      },
    });

    // Configure Nodemailer
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.NODE_MAILER_EMAIL,
        pass: process.env.NODE_MAILER_GMAIL_APP_PASSWORD,
      },
    });

    // Verify transporter
    await transporter.verify();

    // Send email to owner
    try {
      await transporter.sendMail({
        from: process.env.NODE_MAILER_EMAIL,
        to: process.env.NODE_MAILER_EMAIL,
        subject: "New Contact Form Submission from - AutoK",
        html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); background-color: #f8f9fa;">
          <h2 style="background-color: #e53935; color: #fff; padding: 15px; text-align: center; margin: 0; border-top-left-radius: 8px; border-top-right-radius: 8px;">
            🚗 New Contact Form Submission from - AutoK
          </h2>
          <div style="padding: 20px; background-color: #ffffff;">
            <p style="font-size: 16px; color: #555;">You have received a new car inspection request. Here are the details:</p>
            <table style="width: 100%; border-collapse: collapse; background-color: #f8f9fa; color: #333;">
              <tr>
                <td style="padding: 10px; background-color: #e53935; font-weight: bold; color: #fff;">Name:</td>
                <td style="padding: 10px;">${firstName} ${lastName}</td>
              </tr>
              <tr>
                <td style="padding: 10px; background-color: #e53935; font-weight: bold; color: #fff;">Email:</td>
                <td style="padding: 10px;">${email}</td>
              </tr>
              <tr>
                <td style="padding: 10px; background-color: #e53935; font-weight: bold; color: #fff;">VIN Number:</td>
                <td style="padding: 10px;">${vnnumber || "N/A"}</td>
              </tr>
            </table>
            <h3 style="margin-top: 20px; color: #b71c1c;">Message:</h3>
            <p style="background-color: #fff0f0; padding: 15px; border-left: 4px solid #e53935; font-style: italic;">
              ${message}
            </p>
            <p style="margin-top: 20px; font-size: 14px; color: #666;">
              This request was automatically generated by AutoK Car Inspection. Please follow up with the client accordingly.
            </p>
          </div>
          <footer style="background-color: #424242; padding: 10px; text-align: center; font-size: 12px; color: #fff; border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;">
            <strong>AutoK Car Inspection</strong> | Ensuring Quality, One Car at a Time
          </footer>
        </div>
      `,
      });

      // Send confirmation email to customer
      await transporter.sendMail({
        from: process.env.NODE_MAILER_EMAIL,
        to: email,
        subject: "Thank You for Contacting AutoK Car Inspection",
        html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); background-color: #f8f9fa;">
          <h2 style="background-color: #e53935; color: #fff; padding: 15px; text-align: center; margin: 0; border-top-left-radius: 8px; border-top-right-radius: 8px;">
            🚗 Thank You for Contacting AutoK
          </h2>
          <div style="padding: 20px; background-color: #ffffff;">
            <p style="font-size: 16px; color: #555;">
              Dear ${firstName} ${lastName},<br><br>
              Thank you for reaching out to AutoK Car Inspection. We have received your message and will get back to you shortly.
            </p>
            <table style="width: 100%; border-collapse: collapse; background-color: #f8f9fa; color: #333;">
              <tr>
                <td style="padding: 10px; background-color: #e53935; font-weight: bold; color: #fff;">Your Message:</td>
                <td style="padding: 10px;">${message}</td>
              </tr>
            </table>
            <p style="margin-top: 20px; font-size: 16px; color: #555;">
              Our team will review your inquiry and respond within 24 hours. If you need immediate assistance, please don't hesitate to call us.
            </p>
            <p style="font-size: 16px; color: #555;">
              For urgent inquiries, contact us at <a href="mailto:autokinspection@gmail.com" style="color: #e53935;">autokinspection@gmail.com</a>.
            </p>
          </div>
          <footer style="background-color: #424242; padding: 10px; text-align: center; font-size: 12px; color: #fff; border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;">
            <strong>AutoK Car Inspection</strong> | Ensuring Quality, One Car at a Time
          </footer>
        </div>
        `,
      });
    } catch (emailError) {
      console.error("Error sending email:", emailError);
      throw emailError;
    }

    return { success: true, data: contact };
  } catch (error) {
    console.error("Error processing the request:", error);
    return {
      success: false,
      error: "Internal Server Error",
    };
  }
}
